---
- name: Install docker packages
  remote_user: ubuntu
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  tags:
    - docker

- name: Add Docker's official GPG key
  remote_user: ubuntu
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: Verify that we have the key with the fingerprint
  remote_user: ubuntu
  become: yes
  apt_key:
    id: 0EBFCD88
    state: present
  tags:
    - docker

- name: Set up the stable repository
  remote_user: ubuntu
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes
  tags:
    - docker

- name: Update apt packages
  remote_user: ubuntu
  become: yes
  apt:
    update_cache: yes
  tags:
    - docker

- name: Install docker
  remote_user: ubuntu
  become: yes
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  tags:
    - docker

- name: Add remote "ubuntu" user to "docker" group
  remote_user: ubuntu
  become: yes
  user:
    name: "ubuntu"
    group: "docker"
    append: yes
  tags:
    - docker

- name: Install docker-compose
  remote_user: ubuntu
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
  tags:
    - docker

- name: Install other dependencies
  remote_user: ubuntu
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - python3-pip
  tags:
    - docker
